### ISSUE TITLE
Handle tracking.location parameter in API

### ISSUE THREAD

**Issue by marcinkoziej** [fixthestatusquo/proca-server#17]
The default refer policy got more privacy and the HTTP_REFERER we get does not contain path, which might now work for a lot of widget locations (although at least we get the domain name).

- [x] Allow to pass location in a `tracking` parameter of `addActionX` api calls.
- [x] Fall back to `HTTP_REFERER` header
- [x] Send *unhealthy* message to Sentry if both are given but do not match.

**Comment by tttp** [comment]
for sentry: the matching should look only at the domain name, as HTTP_REFER might have the path removed

**Comment by marcinkoziej** [comment]
I think it should look at: `location.startswith(http_referer)` - right ?

**Comment by tttp** [comment]
can I try? where is it deployed?

**Comment by marcinkoziej** [comment]
To live
